#!/usr/bin/env bash

export SAVINGS_DB_HOST=localhost
export SAVINGS_DB_NAME=savings-test
export SAVINGS_DB_USER=juan

script_name=$0
script_full_path=$(dirname "$0")
$script_full_path/savingdeposits --local
